const sampleStudents = [
    {
      id: 1,
      name: "Alice Johnson",
      grade: "A",
      email: "alice@example.com",
      attendance: 95,
      major: "Computer Engineering",
      photo: "https://source.unsplash.com/random/300x300",
    },
    {
      id: 2,
      name: "Bob Smith",
      grade: "B",
      email: "bob@example.com",
      attendance: 88,
      major: "Mechanical Engineering",
      photo: "https://source.unsplash.com/random/300x300?sig=2",
    },
    {
      id: 3,
      name: "Charlie Brown",
      grade: "C",
      email: "charlie@example.com",
      attendance: 92,
      major: "Electrical Engineering",
      photo: "https://source.unsplash.com/random/300x300?sig=3",
    },
    {
      id: 4,
      name: "David Williams",
      grade: "A",
      email: "david@example.com",
      attendance: 98,
      major: "Civil Engineering",
      photo: "https://source.unsplash.com/random/300x300?sig=4",
    },
    {
      id: 5,
      name: "Ella Martinez",
      grade: "B",
      email: "ella@example.com",
      attendance: 89,
      major: "Chemical Engineering",
      photo: "https://source.unsplash.com/random/300x300?sig=5",
    },
    {
      id: 6,
      name: "Frank Taylor",
      grade: "C",
      email: "frank@example.com",
      attendance: 85,
      major: "Aerospace Engineering",
      photo: "https://source.unsplash.com/random/300x300?sig=6",
    },
    {
      id: 7,
      name: "Grace Lee",
      grade: "A",
      email: "grace@example.com",
      attendance: 96,
      major: "Biomedical Engineering",
      photo: "https://source.unsplash.com/random/300x300?sig=7",
    },
    {
      id: 8,
      name: "Henry Anderson",
      grade: "B",
      email: "henry@example.com",
      attendance: 91,
      major: "Industrial Engineering",
      photo: "https://source.unsplash.com/random/300x300?sig=8",
    },
    {
      id: 9,
      name: "Isabella Thomas",
      grade: "A",
      email: "isabella@example.com",
      attendance: 94,
      major: "Environmental Engineering",
      photo: "https://source.unsplash.com/random/300x300?sig=9",
    },
    {
      id: 10,
      name: "Jack Wilson",
      grade: "C",
      email: "jack@example.com",
      attendance: 87,
      major: "Software Engineering",
      photo: "https://source.unsplash.com/random/300x300?sig=10",
    },
  ];

  export default sampleStudents;